### ISSUE TITLE
Rethink how we manage the dependency with r2dii.match

### ISSUE THREAD

**Issue by maurolepore** [RMI-PACTA/r2dii.analysis#351]
Relates to #352 

As of 2021-07-30 I see an error with debian-clang-devel at
https://cran.r-project.org/web/checks/check_results_r2dii.analysis.html

This particular error ultimately comes from an issue in stringdist, and the
maintainer seems to be working on it. However, this also makes me think
we are handling the dependency with r2dii.match in an odd way.

We new only suggest r2dii.match but we enforce it in examples. This is
contradictory. If we want to enforce r2dii.match then we should likley 
add it to Imports -- not Suggests. Or if we want users to opt out of
installing r2dii.match, then we should not throw an error if it's not 
installed. 

Given we expect users of r2dii.analysis to indeed use r2dii.match, I think
the simplest more reasanable soluiton is to add r2dii.match to Imports.

Alternatively we could keep r2dii.match in Suggests and either a) not
run the example where it's needed, or b) export a dataset from r2dii.analysis
that bypasses the need for r2dii.match.

**Comment by jdhoffa** [comment]
> Relates to #352
> 
> As of 2021-07-30 I see an error with debian-clang-devel at https://cran.r-project.org/web/checks/check_results_r2dii.analysis.html
> 
> This particular error ultimately comes from an issue in stringdist, and the maintainer seems to be working on it. However, this also makes me think we are handling the dependency with r2dii.match in an odd way.
> 
> We new only suggest r2dii.match but we enforce it in examples. This is contradictory. If we want to enforce r2dii.match then we should likley add it to Imports -- not Suggests. Or if we want users to opt out of installing r2dii.match, then we should not throw an error if it's not installed.
> 
> Given we expect users of r2dii.analysis to indeed use r2dii.match, I think the simplest more reasanable soluiton is to add r2dii.match to Imports.
> 
> Alternatively we could keep r2dii.match in Suggests and either a) not run the example where it's needed, or b) export a dataset from r2dii.analysis that bypasses the need for r2dii.match.

Hey @maurolepore long time no talk! 

Doing a bit of spring cleaning on these packages, and I attempted to move the `r2dii.match` from `Suggests` to `Imports`, but R CMD check started complaining about "depending on `r2dii.match` but not importing or using any functions from it".

In your experience, what would be a good way to proceed here? I tend to agree that it shouldn't be a hard dependency since we aren't actually using any functions in any of the source code (e.g. I think `r2dii.match` should stay in `Suggests` even if examples assume it is installed)... Would an approach be to wrap the example in a `if` statement that checks if the package is installed first?

**Comment by maurolepore** [comment]
Yeah, sounds like a good case to list it under Suggests and use it conditionally -- maybe with `@examplesIf`?

https://github.com/search?q=org%3Atidyverse+%22%40examplesIf%22&type=code

**Comment by jdhoffa** [comment]
Thanks @maurolepore :-)
